export type Specialist = {
  id: number;
  name: string;
  title: string;
  category: string;
  subcategory: string;
  phone: string;
  website: string;
  social: string;
  instagram: string;
  description: string;
  communityMatch: boolean;
  avatar: string;
  instagramTitle: string;
  instagramFollowers: string;
  instagramFollowing: string;
  instagramBio: string;
  instagramStatus: string;
};

export const specialists: Specialist[] = [
  {
    "id": 1,
    "name": "Єлизавета",
    "title": "Yelyzaveta Hair",
    "category": "Краса",
    "subcategory": "Волосся",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/yelyzaveta_hair_",
    "instagram": "yelyzaveta_hair_",
    "description": "Рекомендовали как мастера по кератину",
    "communityMatch": false,
    "avatar": "/avatars/yelyzaveta_hair_.jpg",
    "instagramTitle": "КЕРАТИН БОТОКС ОБУЧЕНИЕ КАТОВИЦЕ |KERATYNA KATOWICE",
    "instagramFollowers": "1,544",
    "instagramFollowing": "1,510",
    "instagramBio": "Бережно сохраняю прикорневой объём Эффект 4–6 месяцев без утяжеления Уютная студия в центре Катовице Обучение с нуля,...",
    "instagramStatus": "ok"
  },
  {
    "id": 2,
    "name": "Даша",
    "title": "Dashery Stylist",
    "category": "Краса",
    "subcategory": "Волосся",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/dashery_stylist_kr",
    "instagram": "dashery_stylist_kr",
    "description": "Рекомендовали как мастера по кератину",
    "communityMatch": false,
    "avatar": "/avatars/dashery_stylist_kr.jpg",
    "instagramTitle": "ПАРИКМАХЕР КОЛОРИСТ Катовице Перукар Колорист Катовіце",
    "instagramFollowers": "3,321",
    "instagramFollowing": "763",
    "instagramBio": "Дарʼя Колорист Перукар| UGC 🤍Створюю шедеври на волоссі☞ Виправлю усе⁣⁣ 🎓Колористика Навчання ☞ Найскладніші фарбування...",
    "instagramStatus": "ok"
  },
  {
    "id": 3,
    "name": "Ольга",
    "title": "Olga Massage Katowice",
    "category": "Здоровʼя",
    "subcategory": "Масаж",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/olga.massage.katowice",
    "instagram": "olga.massage.katowice",
    "description": "Адрес: Katowice, ул. Jordana, прямо напротив трамвайной остановки",
    "communityMatch": false,
    "avatar": "/avatars/olga.massage.katowice.jpg",
    "instagramTitle": "Масаж Катовіце | Masaż Katowice | Навчання масажу Катовіце",
    "instagramFollowers": "1,885",
    "instagramFollowing": "659",
    "instagramBio": "🔹 12 років досвіду 🔹 Дипломований спеціаліст по масажу 🔹 Медична освіта 🔹 -5 кг після курсу антицелюлітного масажу...",
    "instagramStatus": "ok"
  },
  {
    "id": 4,
    "name": "",
    "title": "Perfect Nails Katowice",
    "category": "Краса",
    "subcategory": "Нігті",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/perfect_nails_katowice",
    "instagram": "perfect_nails_katowice",
    "description": "Маникюр, район Bogucice (в парке на Bogucicka). В тексте прямо: \"працює майстер наш\"",
    "communityMatch": true,
    "avatar": "/avatars/perfect_nails_katowice.jpg",
    "instagramTitle": "Elena Neskorodieva",
    "instagramFollowers": "340",
    "instagramFollowing": "306",
    "instagramBio": "Elena Neskorodieva - Paznokcie Katowice - Manikiur hybrydowy - Manikiur żelowy - Pedikiur",
    "instagramStatus": "ok"
  },
  {
    "id": 5,
    "name": "",
    "title": "Strefa 13 & Brwi",
    "category": "Краса",
    "subcategory": "Брови",
    "phone": "",
    "website": "https://booksy.com/pl-pl/dl/show-business/231929",
    "social": "",
    "instagram": "",
    "description": "Брови / ламинирование, запись через Booksy",
    "communityMatch": false,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 6,
    "name": "",
    "title": "vean_tattoo_katowice",
    "category": "Краса",
    "subcategory": "Пірсинг / тату",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/vean_tattoo_katowice",
    "instagram": "vean_tattoo_katowice",
    "description": "Рекомендовали как мастера по пирсингу",
    "communityMatch": false,
    "avatar": "/avatars/vean_tattoo_katowice.jpg",
    "instagramTitle": "VEAN TATTOO",
    "instagramFollowers": "11.2k",
    "instagramFollowing": "1,115",
    "instagramBio": "VEAN TATTOO - Największa sieć tattoo-studio w Europie - Tattoo Piercing Szkolenia Laser...",
    "instagramStatus": "ok"
  },
  {
    "id": 7,
    "name": "",
    "title": "Нотариус",
    "category": "Юридичні послуги",
    "subcategory": "Нотаріус",
    "phone": "+48 888 094 067",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Рекомендовали в ответ на вопрос про юриста/нотариуса",
    "communityMatch": false,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 8,
    "name": "",
    "title": "moskalova.brows",
    "category": "Краса",
    "subcategory": "Брови",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/moskalova.brows",
    "instagram": "moskalova.brows",
    "description": "Работает в центре, напротив суперсама",
    "communityMatch": false,
    "avatar": "/avatars/moskalova.brows.jpg",
    "instagramTitle": "БРОВИ ЛАМІ ВІЙ КУРСИ КАТОВІЦЕ | BRWI LAMINACJA RZĘS KATOWICE",
    "instagramFollowers": "1,263",
    "instagramFollowing": "126",
    "instagramBio": "Даяна майстер брів & ламі, чую що хочеш - навіть якщо сама ще не знаєш, своя UA у Katowice, 6 років в beauty...",
    "instagramStatus": "ok"
  },
  {
    "id": 9,
    "name": "",
    "title": "Floversnail",
    "category": "Краса",
    "subcategory": "Нігті",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Салон маникюра, адрес: ул. Театральна 9",
    "communityMatch": false,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 10,
    "name": "",
    "title": "nails_koshuba.pl",
    "category": "Краса",
    "subcategory": "Нігті",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/nails_koshuba.pl",
    "instagram": "nails_koshuba.pl",
    "description": "Рекомендовали как маникюрный салон в центре Катовице",
    "communityMatch": false,
    "avatar": "/avatars/nails_koshuba.pl.jpg",
    "instagramTitle": "Manicure Pedicure Katowice Манікюр Педікюр Навчання Катовіце",
    "instagramFollowers": "524",
    "instagramFollowing": "272",
    "instagramBio": "Idealny manicure w 1,5 godziny - 6 lat doświadczenia - Trwałość i jakość aż do 3 tygodni - Pracuję 7 dni w tygodniu...",
    "instagramStatus": "ok"
  },
  {
    "id": 11,
    "name": "",
    "title": "dr__maya",
    "category": "Здоровʼя",
    "subcategory": "Педіатр",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/dr__maya",
    "instagram": "dr__maya",
    "description": "Педиатр, дерматолог и аллерголог; консультация недешёвая. Также упомянута клиника baddi.clinic. В тексте прямо: \"Ось наш педіатр\"",
    "communityMatch": true,
    "avatar": "/avatars/dr__maya.jpg",
    "instagramTitle": "Майя Руселевич • АЛЕРГОЛОГ • ПЕДІАТР • ПУЛЬМОНОЛОГ",
    "instagramFollowers": "78k",
    "instagramFollowing": "386",
    "instagramBio": "Кандидатка медичних наук; 20 років досвіду - Консультую в Direct - Healthy lifestyle doctor @dr.maya_lifestyle...",
    "instagramStatus": "ok"
  },
  {
    "id": 12,
    "name": "",
    "title": "dr.petrenko_olga",
    "category": "Здоровʼя",
    "subcategory": "Педіатр",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/dr.petrenko_olga",
    "instagram": "dr.petrenko_olga",
    "description": "Ведёт троих детей подруги уже 2 года, доказательный врач, ничего лишнего не назначает",
    "communityMatch": true,
    "avatar": "/avatars/dr.petrenko_olga.jpg",
    "instagramTitle": "Педіатр онлайн.Атопічний дерматит.Кашель.Прикорм.ГВ",
    "instagramFollowers": "25.4k",
    "instagramFollowing": "1,235",
    "instagramBio": "Педіатр онлайн, досвід 10+ років - Здобуваю другу вищу магістр нутріціології - Здоров’я дитини без паніки...",
    "instagramStatus": "ok"
  },
  {
    "id": 13,
    "name": "Олег",
    "title": "NL Clinic",
    "category": "Здоровʼя",
    "subcategory": "Стоматолог",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Пломба детского зуба — 250 zl. Пришли по рекомендации из местных чатов, подход врача понравился. Позже уточнили: \"у них є як дорослий кабінет(там працюють наші) так і дитячий кабінет(лікар полька, але дуже уважна)\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 14,
    "name": "",
    "title": "ladna.ja",
    "category": "Краса",
    "subcategory": "Епіляція",
    "phone": "",
    "website": "",
    "social": "https://instagram.com/ladna.ja",
    "instagram": "ladna.ja",
    "description": "Сахарная и лазерная эпиляция. Позже подтверждено: \"Весь персонал українці\"",
    "communityMatch": true,
    "avatar": "/avatars/ladna.ja.jpg",
    "instagramTitle": "LadnaJa • studio pięknego ciała • Katowice, Łódź",
    "instagramFollowers": "3,085",
    "instagramFollowing": "59",
    "instagramBio": "Modelujemy ciało z precyzją i pasją - Kriolipoliza, Kawitacja ultradźwiękowа, Zabiegi wyszczuplające, Nowoczesna...",
    "instagramStatus": "ok"
  },
  {
    "id": 15,
    "name": "",
    "title": "beauty.fairy.s",
    "category": "Краса",
    "subcategory": "Вії",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/beauty.fairy.s",
    "instagram": "beauty.fairy.s",
    "description": "Наращивание/коррекция ресниц, район Sosnowiec Pogoń",
    "communityMatch": false,
    "avatar": "/avatars/beauty.fairy.s.jpg",
    "instagramTitle": "KOSMETYCZNA STUDIA | SOSNOWIEC",
    "instagramFollowers": "127",
    "instagramFollowing": "47",
    "instagramBio": "twój wygląd w rękach mistrza - paznokcie ta brwi za 2 godziny - gwarancja na usługi 5 dni",
    "instagramStatus": "ok"
  },
  {
    "id": 16,
    "name": "Анастасія",
    "title": "Анастасія",
    "category": "Їжа",
    "subcategory": "Кондитер",
    "phone": "+48881295078",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Может испечь кондитерские изделия (не срочно)",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 17,
    "name": "Есхан Юзефіан",
    "title": "Pixel Clinic",
    "category": "Здоровʼя",
    "subcategory": "Стоматолог",
    "phone": "",
    "website": "https://pixelclinic.pl",
    "social": "https://www.instagram.com/dr.ehsan.yousefian_",
    "instagram": "dr.ehsan.yousefian_",
    "description": "Врач из Украины, можно написать в инсту с вопросами перед консультацией",
    "communityMatch": true,
    "avatar": "/avatars/dr.ehsan.yousefian_.jpg",
    "instagramTitle": "Эхсан Юсефиан",
    "instagramFollowers": "531",
    "instagramFollowing": "1,097",
    "instagramBio": "Др.Эхсан Юсефиан - Детский стоматолог - Главный врач клиники Kids Dental - Лечение зубов во сне - Лечение детей от 0 [PRIVATE PROFILE - posts not visible]",
    "instagramStatus": "ok"
  },
  {
    "id": 18,
    "name": "",
    "title": "Czarodziejki",
    "category": "Краса",
    "subcategory": "Салон краси",
    "phone": "",
    "website": "",
    "social": "https://booksy.com/pl-pl/dl/show-business/308237",
    "instagram": "",
    "description": "Есть места в Ruda Śląska, запись через Booksy",
    "communityMatch": false,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 19,
    "name": "Yuliia Vereta",
    "title": "Yuliia Vereta",
    "category": "Послуги",
    "subcategory": "Перекладач",
    "phone": "",
    "website": "",
    "social": "Facebook: Yuliia Vereta",
    "instagram": "",
    "description": "Перевод аттестата с украинского на польский",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 20,
    "name": "",
    "title": "Без назви",
    "category": "Послуги",
    "subcategory": "Перекладач",
    "phone": "",
    "website": "",
    "social": "https://www.facebook.com/share/1CMo7Cg7nM",
    "instagram": "",
    "description": "Рекомендовали как переводчика — адекватные цены и быстрые сроки",
    "communityMatch": false,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 21,
    "name": "Олег",
    "title": "Олег",
    "category": "Нерухомість",
    "subcategory": "Рієлтор",
    "phone": "",
    "website": "",
    "social": "Telegram: @oleh_rental",
    "instagram": "",
    "description": "Занимается арендой и продажей квартир",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 22,
    "name": "",
    "title": "Без назви",
    "category": "Інше",
    "subcategory": "Не вказано",
    "phone": "",
    "website": "",
    "social": "Telegram: @valeriiache3",
    "instagram": "",
    "description": "Рекомендовали дважды по разным поводам — как SMM-специалиста (#18436) и как риелтора (#18516), категория неочевидна — уточнить вручную",
    "communityMatch": false,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 23,
    "name": "",
    "title": "receptaekspres.pl",
    "category": "Здоровʼя",
    "subcategory": "Онлайн-рецепти",
    "phone": "",
    "website": "https://receptaekspres.pl",
    "social": "",
    "instagram": "",
    "description": "Сервис заказа рецепта онлайн",
    "communityMatch": false,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 24,
    "name": "",
    "title": "zaufanarecepta.pl",
    "category": "Здоровʼя",
    "subcategory": "Онлайн-рецепти",
    "phone": "",
    "website": "https://zaufanarecepta.pl",
    "social": "",
    "instagram": "",
    "description": "Сервис заказа рецепта онлайн",
    "communityMatch": false,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 25,
    "name": "Ольга Ромашкова",
    "title": "Ольга Ромашкова",
    "category": "Краса",
    "subcategory": "Косметолог",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/olya_romashkova_cosmetology",
    "instagram": "olya_romashkova_cosmetology",
    "description": "Косметолог-дерматолог, работает в т.ч. с подростками",
    "communityMatch": true,
    "avatar": "/avatars/olya_romashkova_cosmetology.jpg",
    "instagramTitle": "Romashkova Skin Aesthetics Clinic | Anti-age & Laser Clinic",
    "instagramFollowers": "4,976",
    "instagramFollowing": "795",
    "instagramBio": "Estetyczna i iniekcyjna kosmetologia - Laser CO2 IPL Morpheus8 - Anti-age терапії та сучасні методики - 10+...",
    "instagramStatus": "ok"
  },
  {
    "id": 26,
    "name": "Надія",
    "title": "Надія",
    "category": "Краса",
    "subcategory": "Епіляція (шугаринг)",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Мастер шугаринга, центр Катовице, запись в личные сообщения",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 27,
    "name": "Вікторія Дрон",
    "title": "M&M Legally Company",
    "category": "Юридичні послуги",
    "subcategory": "Легалізація / карта побиту",
    "phone": "+48 889 033 366",
    "website": "",
    "social": "TikTok: 3107.viktoriia_dron",
    "instagram": "",
    "description": "Помогает с оформлением карты побыту, есть офис в центре. Адрес: Przemysłowa 10/226, Katowice",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 28,
    "name": "Леся Вовнянко",
    "title": "Леся Вовнянко",
    "category": "Здоровʼя",
    "subcategory": "Психіатр",
    "phone": "",
    "website": "https://psychomedic.pl/specjalisci/dr-lesia-vovnianko/",
    "social": "",
    "instagram": "",
    "description": "Можно записаться онлайн; неясно, выдаёт ли справки (Л4)",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 29,
    "name": "Яніна Шиманська",
    "title": "Яніна Шиманська",
    "category": "Здоровʼя",
    "subcategory": "Гінеколог",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/yanina_shymanska",
    "instagram": "yanina_shymanska",
    "description": "Принимает в клинике Zdorovo в Катовице",
    "communityMatch": true,
    "avatar": "/avatars/yanina_shymanska.jpg",
    "instagramTitle": "Yanina Shymanska",
    "instagramFollowers": "3,894",
    "instagramFollowing": "2,624",
    "instagramBio": "Акушер-гінеколог, Статеве виховання - УЗД, Питання про гормони - Online консультації - Katowice...",
    "instagramStatus": "ok"
  },
  {
    "id": 30,
    "name": "Ірина",
    "title": "Ірина",
    "category": "Здоровʼя",
    "subcategory": "Фізіотерапевт / масажист",
    "phone": "",
    "website": "",
    "social": "https://www.facebook.com/share/1DHCs9ZHqe/",
    "instagram": "",
    "description": "Рекомендовали как отличного специалиста в ответ на запрос массажиста",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 31,
    "name": "Вадим",
    "title": "Вадим Транспорт",
    "category": "Транспорт",
    "subcategory": "Вантажні перевезення / переїзди",
    "phone": "+48 574 152 281",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Услуги перевозчика (грузовое такси)",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 32,
    "name": "Ася",
    "title": "Ася",
    "category": "Освіта",
    "subcategory": "Репетитор англійської мови",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Более 3 лет преподаёт английский, образование по специальности \"Початкова освіта\" с углублённым изучением украинского и английского",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 33,
    "name": "Аліна",
    "title": "dr.alina_katowice",
    "category": "Краса",
    "subcategory": "Збільшення губ",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/dr.alina_katowice",
    "instagram": "dr.alina_katowice",
    "description": "Рекомендована в ответ на вопрос про увеличение губ",
    "communityMatch": true,
    "avatar": "/avatars/dr.alina_katowice.jpg",
    "instagramTitle": "Kosmetologist 📍Odesa-Katowice",
    "instagramFollowers": "2,363",
    "instagramFollowing": "849",
    "instagramBio": "Высшее медицинское образование ОНМедУ - Аппаратная и инъекционная косметология - Ботокс Филлеры Биоревитализация...",
    "instagramStatus": "ok"
  },
  {
    "id": 34,
    "name": "Вікторі",
    "title": "Вікторі",
    "category": "Краса",
    "subcategory": "Колорист (фарбування волосся)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/viktori.nice.hair",
    "instagram": "viktori.nice.hair",
    "description": "Рекомендована как хороший колорист для блонда",
    "communityMatch": true,
    "avatar": "/avatars/viktori.nice.hair.jpg",
    "instagramTitle": "ПЕРУКАР | Fryzjer | 🇵🇱 Katowice",
    "instagramFollowers": "2,499",
    "instagramFollowing": "3,196",
    "instagramBio": "Засновниця: @vedantahair - Стрижки Фарбування СПА-догляд - Працюю з текстурою - Відновлюю структуру, створюю форму",
    "instagramStatus": "ok"
  },
  {
    "id": 35,
    "name": "Вікторія та Катерина",
    "title": "Crystal Katowice",
    "category": "Краса",
    "subcategory": "Нігті",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/crystal_katowice",
    "instagram": "crystal_katowice",
    "description": "Качественный маникюр, рекомендовали в ответ на вопрос про мастера в Катовице/Хожуве. Позже подтверждено: \"В салоні працюють наші дівчата, все зроблено з українською душою\"",
    "communityMatch": true,
    "avatar": "/avatars/crystal_katowice.jpg",
    "instagramTitle": "SALON BEAUTY KATOWICE • fryzjer • paznokcie • kosmetologia",
    "instagramFollowers": "1,599",
    "instagramFollowing": "125",
    "instagramBio": "Sztuka piękna dopracowanego w każdym detalu - Zadbamy o Twój wygląd od stóp do głów - Sprawdź naszą ofertę i umów...",
    "instagramStatus": "ok"
  },
  {
    "id": 36,
    "name": "",
    "title": "Torry Hair Studio",
    "category": "Краса",
    "subcategory": "Волосся",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/torry_hair_studio",
    "instagram": "torry_hair_studio",
    "description": "Рекомендовали, ходили год назад — остались довольны",
    "communityMatch": false,
    "avatar": "/avatars/torry_hair_studio.jpg",
    "instagramTitle": "FRYZJER-KOLORYSTA •TRWAŁA Ondulacja 📍KATOWICE🇺🇦🇵🇱",
    "instagramFollowers": "354",
    "instagramFollowing": "288",
    "instagramBio": "Dbam o zdrowie włosów i pełne zadowolenie klientów - Farbowanie, total blond, trwała ondulacja, odbudowa włosów",
    "instagramStatus": "ok"
  },
  {
    "id": 37,
    "name": "Петро",
    "title": "Петро",
    "category": "Послуги",
    "subcategory": "Ремонт кавомашин",
    "phone": "",
    "website": "",
    "social": "https://www.facebook.com/share/1Df1U5Kbze/",
    "instagram": "",
    "description": "\"Чудовий майстер\" — рекомендовали для ремонта кофемашины",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 38,
    "name": "",
    "title": "Alledoctor",
    "category": "Здоровʼя",
    "subcategory": "Лікар загальної практики",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/alledoctor",
    "instagram": "alledoctor",
    "description": "В тексте прямо указано: \"Це український лікар\"",
    "communityMatch": true,
    "avatar": "/avatars/alledoctor.jpg",
    "instagramTitle": "Дмитро | лікар в Польщі| Лодзь | Варшава",
    "instagramFollowers": "17.7k",
    "instagramFollowing": "66",
    "instagramBio": "Швидкий прийом пацієнтів без тривалих черг - Languages: українська, русский, polski, english - Консультації онлайн...",
    "instagramStatus": "ok"
  },
  {
    "id": 39,
    "name": "Катерина Бакіко",
    "title": "Катерина Бакіко",
    "category": "Здоровʼя",
    "subcategory": "Дерматолог (дитячий)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/dr.kateryna_bakiko",
    "instagram": "dr.kateryna_bakiko",
    "description": "Рекомендовали в ответ на вопрос про хорошего детского дерматолога",
    "communityMatch": true,
    "avatar": "/avatars/dr.kateryna_bakiko.jpg",
    "instagramTitle": "ДЕРМАТОЛОГ | ЛЬВІВ | ОНЛАЙН",
    "instagramFollowers": "115k",
    "instagramFollowing": "95",
    "instagramBio": "Дитячий та дорослий дерматолог, трихолог - Доказова медицина - Міжнародна сертифікація - Школа атопічного дерматиту",
    "instagramStatus": "ok"
  },
  {
    "id": 40,
    "name": "",
    "title": "Нотариус (Украина)",
    "category": "Юридичні послуги",
    "subcategory": "Нотаріус / довіреність",
    "phone": "+380979990202",
    "website": "",
    "social": "Viber: +380979990202",
    "instagram": "",
    "description": "Помогает оформить доверенность дистанционно, украинский номер телефона",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 41,
    "name": "Iryna Hetsko",
    "title": "Iryna Hetsko",
    "category": "Здоровʼя",
    "subcategory": "Психолог",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Психолог (КПТ, ТПВ), проводит бесплатные онлайн-консультации; сама пишет пост на украинском, представляется как \"психологиня\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 42,
    "name": "Юлія Рижак",
    "title": "Studio by Yuliia Ryzhak",
    "category": "Краса",
    "subcategory": "Волосся",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/studio_by_yuliia_ryzhak",
    "instagram": "studio_by_yuliia_ryzhak",
    "description": "Рекомендовали, работает недалеко от центра Катовице",
    "communityMatch": true,
    "avatar": "/avatars/studio_by_yuliia_ryzhak.jpg",
    "instagramTitle": "DEPILACJA CIAŁA ZA 1 GODZINĘ•PRZEDŁUŻANIE RZĘS ZA 110 MIN",
    "instagramFollowers": "576",
    "instagramFollowing": "5,032",
    "instagramBio": "Hejka, jestem Julia - Depilacja ciała za 1 godzinę - Przedłużania rzęs 110 min - Aby dokonać rezerwacji napisz do Direct",
    "instagramStatus": "ok"
  },
  {
    "id": 43,
    "name": "Ірина",
    "title": "Ірина",
    "category": "Здоровʼя",
    "subcategory": "Масаж",
    "phone": "",
    "website": "",
    "social": "https://www.facebook.com/share/18panbvguX/",
    "instagram": "",
    "description": "Рекомендовали в ответ на вопрос про массажиста",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 44,
    "name": "Lena Kovalova",
    "title": "Lena Kovalova",
    "category": "Краса",
    "subcategory": "Волосся (колорист)",
    "phone": "",
    "website": "",
    "social": "Telegram: @Lena_Kovalova",
    "instagram": "",
    "description": "Рекомендовали как хорошего парикмахера-колориста",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 45,
    "name": "Ira",
    "title": "APN Katowice (бухгалтерское бюро)",
    "category": "Фінанси",
    "subcategory": "Бухгалтер",
    "phone": "",
    "website": "https://apn.katowice.pl",
    "social": "",
    "instagram": "",
    "description": "\"Є украінські і польські бухгалтери\" — прямое указание на украинских специалистов в бюро",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 46,
    "name": "Ірина Карпова",
    "title": "Ірина Карпова",
    "category": "Юридичні послуги",
    "subcategory": "Сімейне право (дистанційно)",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Расторжение брака, раздел имущества, алименты — дистанционно, без выезда в Украину",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 47,
    "name": "Lena Konovalova",
    "title": "Lena Konovalova",
    "category": "Здоровʼя",
    "subcategory": "Подолог",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/lena_konovalova_podolog",
    "instagram": "lena_konovalova_podolog",
    "description": "Рекомендовали в ответ на вопрос про хорошего подолога",
    "communityMatch": true,
    "avatar": "/avatars/lena_konovalova_podolog.jpg",
    "instagramTitle": "PODOLOGIA MANICURE PEDICURE KATOWICE",
    "instagramFollowers": "775",
    "instagramFollowing": "250",
    "instagramBio": "YOUR BEAUTY PLACE STUDIO - про роботу та особисте - PODOLOGIA/Подологія MANICURE/Манікюр PEDICURE/Педикюр",
    "instagramStatus": "ok"
  },
  {
    "id": 48,
    "name": "",
    "title": "Podolog Katowice",
    "category": "Здоровʼя",
    "subcategory": "Подолог",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/podolog_katowice_",
    "instagram": "podolog_katowice_",
    "description": "Рекомендовали как подолога",
    "communityMatch": false,
    "avatar": "/avatars/podolog_katowice_.jpg",
    "instagramTitle": "Александра Торговцова",
    "instagramFollowers": "566",
    "instagramFollowing": "857",
    "instagramBio": "ponad 15 lat w podologii - Terapia wrastających paznokci bez bólu - Pedicure, opracowanie...",
    "instagramStatus": "ok"
  },
  {
    "id": 49,
    "name": "",
    "title": "Liona Stylist",
    "category": "Краса",
    "subcategory": "Волосся",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/liona.stylist",
    "instagram": "liona.stylist",
    "description": "\"Щиро рекомендую\" — стилист по волосам",
    "communityMatch": false,
    "avatar": "/avatars/liona.stylist.jpg",
    "instagramTitle": "Natalia Levchenko | Hair • Makeup • Color | Katowice",
    "instagramFollowers": "1,169",
    "instagramFollowing": "337",
    "instagramBio": "Hair & Makeup Artist - Bridal Event Colorist - Milan Fashion Week 2023 Team - Katowice",
    "instagramStatus": "ok"
  },
  {
    "id": 50,
    "name": "Анастасия",
    "title": "Анастасия",
    "category": "Здоровʼя",
    "subcategory": "Психолог",
    "phone": "",
    "website": "",
    "social": "Instagram: psy.anastasiia._",
    "instagram": "",
    "description": "Онлайн-консультации, 1 час, самопост",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 51,
    "name": "Ольга Зіненко",
    "title": "Kolorysta Olga Zinenko",
    "category": "Краса",
    "subcategory": "Волосся (колорист)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/kolorysta_olgazinenko",
    "instagram": "kolorysta_olgazinenko",
    "description": "В имени профиля указаны флаги 🇺🇦🇵🇱 — колорист/стилист, Катовице",
    "communityMatch": true,
    "avatar": "/avatars/kolorysta_olgazinenko.jpg",
    "instagramTitle": "KOLORIST | KATOWICE | ВІДНОВЛЕННЯ ВОЛОССЯ",
    "instagramFollowers": "1,662",
    "instagramFollowing": "522",
    "instagramBio": "Specjalistka od strzyżenia, koloryzacji i regeneracji włosów - 16 lat doświadczenia - Efekt zdrowych, lśniących...",
    "instagramStatus": "ok"
  },
  {
    "id": 52,
    "name": "",
    "title": "Клиника (без названия)",
    "category": "Здоровʼя",
    "subcategory": "Психіатр",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Рекомендовали клинику, где можно записаться к психиатру-украинке, есть онлайн-приём; также есть психотерапевт в гештальт-подходе",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 53,
    "name": "",
    "title": "Studio Roxe",
    "category": "Послуги",
    "subcategory": "Пошиття (косметички на замовлення)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/studioroxe",
    "instagram": "studioroxe",
    "description": "В тексте прямо: \"дівчина українка шиє косметички\", работает под заказ",
    "communityMatch": true,
    "avatar": "/avatars/studioroxe.jpg",
    "instagramTitle": "",
    "instagramFollowers": "1,699",
    "instagramFollowing": "110",
    "instagramBio": "Kosmetyczki & akcesoria do włosów - Zamówienia przez Direct - Based in Poland",
    "instagramStatus": "ok"
  },
  {
    "id": 54,
    "name": "Julenka",
    "title": "Julenka",
    "category": "Здоровʼя",
    "subcategory": "Косметолог (онлайн, акне)",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"Могу порекомендовать с Киева — проводит онлайн консультации\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 55,
    "name": "Юлия Соляник",
    "title": "Юлия Соляник",
    "category": "Послуги",
    "subcategory": "Перекладач (укр-пол документи)",
    "phone": "+48 792 234 754",
    "website": "",
    "social": "Viber: +48 792 234 754",
    "instagram": "",
    "description": "Живёт в Катовице, быстро и недорого переводит документы",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 56,
    "name": "Оксана Іванюк",
    "title": "Оксана Іванюк",
    "category": "Краса",
    "subcategory": "Епіляція (шугаринг/віск)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/oksana.ivaniuk_",
    "instagram": "oksana.ivaniuk_",
    "description": "Рекомендовали в ответ на вопрос про шугаринг/восковую депиляцию",
    "communityMatch": true,
    "avatar": "/avatars/oksana.ivaniuk_.jpg",
    "instagramTitle": "DEPILACJA| LASER | ELEKTROLIZA | SZKOLENIE | GLIWICE",
    "instagramFollowers": "687",
    "instagramFollowing": "252",
    "instagramBio": "Depilacja cukrem, woskiem, elektroliza - Laserowa epilacja - Trener szkoły PANDHY’S @pandhys_poland - Zaufaj...",
    "instagramStatus": "ok"
  },
  {
    "id": 57,
    "name": "Влада Монастирська",
    "title": "Влада Монастирська",
    "category": "Послуги",
    "subcategory": "Візове агентство",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/vlada_monastyrska",
    "instagram": "vlada_monastyrska",
    "description": "Офис недалеко от Катовице, работает 10 лет, делает нац. польскую визу без выезда",
    "communityMatch": true,
    "avatar": "/avatars/vlada_monastyrska.jpg",
    "instagramTitle": "✈️🌍Тури • Готелі • Круїзи|Travelagent",
    "instagramFollowers": "2,367",
    "instagramFollowing": "598",
    "instagramBio": "PolFunTravel - Твій персональний турагент - Підберу тур, як для себе - Mikołów(Jana Pawła II 20)",
    "instagramStatus": "ok"
  },
  {
    "id": 58,
    "name": "Наталя",
    "title": "Time to Travel",
    "category": "Послуги",
    "subcategory": "Турагент",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/timetotravel_psn",
    "instagram": "timetotravel_psn",
    "description": "\"Молода продвинута дівчина, в курсі всього найкращого\" — личная рекомендация",
    "communityMatch": true,
    "avatar": "/avatars/timetotravel_psn.jpg",
    "instagramTitle": "Поїхали з нами 🌍 Турагентство",
    "instagramFollowers": "108",
    "instagramFollowing": "22",
    "instagramBio": "Працюємо онлайн - зручно і швидко - З вами на звʼязку Наталія і Яна - 10 років досвіду в туризмі - Більше тисячі...",
    "instagramStatus": "ok"
  },
  {
    "id": 59,
    "name": "Сергій Карпов",
    "title": "Адвокатське бюро «Карпов та Партнери»",
    "category": "Юридичні послуги",
    "subcategory": "Адвокат (право України)",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Юридическая помощь по украинскому праву (развод, раздел имущества и др.) для граждан Украины в стране и за рубежом",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 60,
    "name": "Iryna Yurchak",
    "title": "Iryna Yurchak",
    "category": "Юридичні послуги",
    "subcategory": "Юрист",
    "phone": "530810555",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Рекомендовали именно в ответ на запрос \"Українського Юриста-Адвоката\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 61,
    "name": "Olena Yelchyshcheva",
    "title": "Simply Dental Clinic",
    "category": "Здоровʼя",
    "subcategory": "Стоматолог-ортодонт",
    "phone": "+48326081124",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Ортодонт/стоматолог, ul. Słowackiego 29, Katowice. Запись через Znany Lekarz или сайт Simply Dental",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 62,
    "name": "Svitlana Habaraieva",
    "title": "Svitlana Habaraieva",
    "category": "Освіта",
    "subcategory": "Репетитор польської мови",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Индивидуальные уроки польского, 45 zł/урок, самопост",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 63,
    "name": "",
    "title": "Hairdresser.000",
    "category": "Краса",
    "subcategory": "Волосся (стрижка каре-піксі)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/hairdresser.000",
    "instagram": "hairdresser.000",
    "description": "Рекомендовали именно в ответ на запрос \"українського майстра... каре-піксі\"",
    "communityMatch": true,
    "avatar": "/avatars/hairdresser.000.jpg",
    "instagramTitle": "Yuliia hairdresser ✂️",
    "instagramFollowers": "137",
    "instagramFollowing": "108",
    "instagramBio": "Колорист стилист - 15 лет в сфере красоты - Индивидуальные стрижки - Все виды окрашивания...",
    "instagramStatus": "ok"
  },
  {
    "id": 64,
    "name": "",
    "title": "Już Czas Barbershop",
    "category": "Краса",
    "subcategory": "Барбершоп",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"🇺🇦 Український барбершоп у Катовіце\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 65,
    "name": "",
    "title": "Кав'ярня IRIS",
    "category": "Заклади",
    "subcategory": "Кафе",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Хожув. В тексте прямо: \"Ваша українська кав'ярня IRIS\", говорят по-украински",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 66,
    "name": "Alina",
    "title": "Comfort Trans Dispatcher",
    "category": "Послуги",
    "subcategory": "Перевезення (Катовіце-Київ)",
    "phone": "+38 (097) 692 82 02",
    "website": "",
    "social": "https://www.instagram.com/comfort_trans_dispatcher",
    "instagram": "comfort_trans_dispatcher",
    "description": "Диспетчер, сотрудничают со многими перевозчиками, без предоплаты; украинский номер телефона",
    "communityMatch": true,
    "avatar": "/avatars/comfort_trans_dispatcher.jpg",
    "instagramTitle": "КВИТКИ НА АВТОБУС | СТРАХУВАННЯ | УКРАЇНА - ЄВРОПА",
    "instagramFollowers": "10.9k",
    "instagramFollowing": "14,725",
    "instagramBio": "Квитки та страховка в одному місці - Рейси до 25+ країн Європи - Оплата при посадці, купівля...",
    "instagramStatus": "ok"
  },
  {
    "id": 67,
    "name": "",
    "title": "Українська стоматологія (Тихи)",
    "category": "Здоровʼя",
    "subcategory": "Контактний номер",
    "phone": "",
    "website": "https://www.instagram.com/stomatolog_tychy",
    "social": "Адреса: Aleja Bielska 33, Тихи. Хорошо делают свою работу (если нет воспаления — примут довольно быстро)",
    "instagram": "",
    "description": "Упомянута как известное место (сейчас большая очередь) — название прямо указывает на украинскую стоматологию в Тихах. Также подтверждено: \"працюють тільки наші українці\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 68,
    "name": "Руслан",
    "title": "Руслан",
    "category": "Юридичні послуги",
    "subcategory": "Юрист (легалізація)",
    "phone": "+48 794 236 865",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Консультация по вопросам легализации, ответил на все вопросы",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 69,
    "name": "Катерина",
    "title": "Provet s.c.",
    "category": "Здоровʼя",
    "subcategory": "Ветеринар",
    "phone": "+48 660 755 538",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Klinika weterynaryjna в Семяновице-Слёнске",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 70,
    "name": "",
    "title": "Krawcowa Proff",
    "category": "Послуги",
    "subcategory": "Швачка",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/krawcowa_proff",
    "instagram": "krawcowa_proff",
    "description": "Услуги профессиональной швеи (мама автора поста), Сосновец/Катовице, подшить/зашить/отремонтировать",
    "communityMatch": true,
    "avatar": "/avatars/krawcowa_proff.jpg",
    "instagramTitle": "Професійна кравчиня з дуже великим досвідом 🪡",
    "instagramFollowers": "122",
    "instagramFollowing": "38",
    "instagramBio": "Katowice/Sosnowiec - Кравчиня з 40+ років досвіду - Індивідуальний підхід до кожної ситуації - Зручна локалізація",
    "instagramStatus": "ok"
  },
  {
    "id": 71,
    "name": "Ганна",
    "title": "Ганна",
    "category": "Послуги",
    "subcategory": "Народні ремесла (бісероплетіння, силянка)",
    "phone": "729616335",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Плетёт силянки (традиционные украинские бисерные украшения), рекомендовали как мастера",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 72,
    "name": "",
    "title": "expert_docs_com",
    "category": "Юридичні послуги",
    "subcategory": "Нотаріус / документи",
    "phone": "",
    "website": "",
    "social": "Telegram: @expert_docs_com",
    "instagram": "",
    "description": "Рекомендовали именно в ответ на запрос \"українського нотаріуса\" (доверенность)",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 73,
    "name": "",
    "title": "Перевозчик (Катовице–Николаев)",
    "category": "Послуги",
    "subcategory": "Пасажирські перевезення",
    "phone": "+380636307737",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Ответ на запрос перевозчика Катовице–Николаев; украинский номер телефона",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 74,
    "name": "",
    "title": "Czas Katowice",
    "category": "Заклади",
    "subcategory": "Танцювальна студія",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/czas.katowice",
    "instagram": "czas.katowice",
    "description": "В тексте прямо: \"нашу українську студію\", площадь Ринок, танцы/фитнес/йога в гамаках/Kangoo",
    "communityMatch": true,
    "avatar": "/avatars/czas.katowice.jpg",
    "instagramTitle": "CZAS studio fitness Katowice",
    "instagramFollowers": "2,701",
    "instagramFollowing": "72",
    "instagramBio": "Po raz pierwszy w Katowicach - Rewolucyjne podejście do fitnessu: AERIAL YOGA, LATINA...",
    "instagramStatus": "ok"
  },
  {
    "id": 75,
    "name": "Олександр",
    "title": "Олександр",
    "category": "Послуги",
    "subcategory": "Автомеханік (двигуни)",
    "phone": "511 031 473",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Сосновец, работает и в субботу, и в воскресенье, довольны многие",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 76,
    "name": "Андрей",
    "title": "Андрей",
    "category": "Послуги",
    "subcategory": "Електрик",
    "phone": "+48 538 525 432",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Рекомендовали в ответ на вопрос про хорошего электрика",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 77,
    "name": "Diana Sidletska",
    "title": "Поїхали з нами",
    "category": "Послуги",
    "subcategory": "Турагентство / трансфер",
    "phone": "",
    "website": "",
    "social": "Telegram: @sidletska_diana",
    "instagram": "",
    "description": "Рекомендовали именно в ответ на запрос \"тур агентство. Бажано з українцями\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 78,
    "name": "Максим",
    "title": "Українське СТО (Мисловіце)",
    "category": "Послуги",
    "subcategory": "Автосервіс",
    "phone": "+48 731 351 690",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"Українське СТО в Мисловіцах\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 79,
    "name": "Оля",
    "title": "Studio Beauty Home",
    "category": "Краса",
    "subcategory": "Волосся",
    "phone": "",
    "website": "",
    "social": "https://booksy.com/pl-pl/dl/show-business/194559",
    "instagram": "",
    "description": "В названии на Booksy флаги 🇺🇦🇵🇱 FRYZJER KATOWICE",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 80,
    "name": "",
    "title": "Anastasiia Kots",
    "category": "Краса",
    "subcategory": "Візаж (макіяж)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/anastasiakots.makeup.hair",
    "instagram": "anastasiakots.makeup.hair",
    "description": "Рекомендовали именно в ответ на запрос \"українсько мовного візажиста\"",
    "communityMatch": true,
    "avatar": "/avatars/anastasiakots.makeup.hair.jpg",
    "instagramTitle": "MAKEUP | HAIR KATOWICE | МАКИЯЖ • ОБУЧЕНИЕ КАТОВИЦЕ",
    "instagramFollowers": "5,309",
    "instagramFollowing": "689",
    "instagramBio": "ANASTASIA KOTS - Brides Evening Makeup Artist - Hairstylist - Базовый курс Визажист с 0...",
    "instagramStatus": "ok"
  },
  {
    "id": 81,
    "name": "Катрін",
    "title": "Катрін",
    "category": "Краса",
    "subcategory": "Візаж (макіяж)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/katrinnmakeup",
    "instagram": "katrinnmakeup",
    "description": "Рекомендовали именно в ответ на запрос \"українсько мовного візажиста\"",
    "communityMatch": true,
    "avatar": "/avatars/katrinnmakeup.jpg",
    "instagramTitle": "KATRIN | MAKE UP KATOWICE | HAIR | EDUCATION",
    "instagramFollowers": "2,506",
    "instagramFollowing": "482",
    "instagramBio": "Курс Визажист с 0 - Evening Wedding Make Up Hairstyle - Makeup Artist and Hairstylist - Katowice, Poland",
    "instagramStatus": "ok"
  },
  {
    "id": 82,
    "name": "Марина",
    "title": "Марина",
    "category": "Здоровʼя",
    "subcategory": "Фізіотерапевт (дитячий)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/marina_zalizovskaja",
    "instagram": "marina_zalizovskaja",
    "description": "Рекомендовали в ответ на вопрос про физиотерапевта для младенца",
    "communityMatch": true,
    "avatar": "/avatars/marina_zalizovskaja.jpg",
    "instagramTitle": "ФІЗИЧНИЙ РОЗВИТОК ПЛАВАННЯ НЕМОВЛЯТ | Тихи | Катовіце",
    "instagramFollowers": "1,316",
    "instagramFollowing": "651",
    "instagramBio": "Фізичний розвиток Плавання - 15+ років досвіду - працюю з немовлятами 0+ - Онлайн-консультація та супровід",
    "instagramStatus": "ok"
  },
  {
    "id": 83,
    "name": "Світлана",
    "title": "Світлана",
    "category": "Юридичні послуги",
    "subcategory": "Адвокат (сімейне право)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/advokat_law_for_all",
    "instagram": "advokat_law_for_all",
    "description": "Рекомендовали именно в ответ на запрос \"адвоката по сімейним справам. Бажано українець\"",
    "communityMatch": true,
    "avatar": "/avatars/advokat_law_for_all.jpg",
    "instagramTitle": "Svitlana Savenko - АДВОКАТ ОНЛАЙН ЮРИСТ ПОМОЩЬ БИЗНЕСУ",
    "instagramFollowers": "5,019",
    "instagramFollowing": "499",
    "instagramBio": "Развод, алименты, раздел имущества, наследство, кредиты - Новая основная страница @advokat_law_for_all_",
    "instagramStatus": "ok"
  },
  {
    "id": 84,
    "name": "Альона",
    "title": "Альона",
    "category": "Краса",
    "subcategory": "Косметолог",
    "phone": "+48731494858",
    "website": "",
    "social": "Telegram/Instagram: @heyalyonaa",
    "instagram": "",
    "description": "Личная рекомендация, подбирает уход под кожу, принимает в центре Катовице",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 85,
    "name": "",
    "title": "Kancelaria Kutsko",
    "category": "Юридичні послуги",
    "subcategory": "Юрист (міграційне право)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/kancelaria_kutsko",
    "instagram": "kancelaria_kutsko",
    "description": "Рекомендовали как миграционного юриста",
    "communityMatch": true,
    "avatar": "/avatars/kancelaria_kutsko.jpg",
    "instagramTitle": "ЛЕГАЛИЗАЦИЯ | ЮРИДИЧЕСКИЕ УСЛУГИ | ПОЛЬША МЕЖДУНАРОДНАЯ ЗАЩИТА",
    "instagramFollowers": "32.7k",
    "instagramFollowing": "1",
    "instagramBio": "Бессрочное право пребывания в Польше на основании международной защиты - За 4+ года 1987 дел - Оформим гражданство без ПМ...",
    "instagramStatus": "ok"
  },
  {
    "id": 86,
    "name": "Отець Олег",
    "title": "Українська церква (Катовіце)",
    "category": "Заклади",
    "subcategory": "Церква",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Крестят детей; упомянута как \"наша укр церква в Катовіце\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 87,
    "name": "",
    "title": "Soniadei",
    "category": "Краса",
    "subcategory": "Тату",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/soniadei",
    "instagram": "soniadei",
    "description": "Рекомендовали как тату-мастера; в тексте прямо: \"Українка\"",
    "communityMatch": true,
    "avatar": "/avatars/soniadei.jpg",
    "instagramTitle": "Sonia Dei / Tattoo / Katowice",
    "instagramFollowers": "25.2k",
    "instagramFollowing": "713",
    "instagramBio": "TATTOO w Katowice @astattookatowice - Z dbałością o detale przeniosę Twój pomysł na skórę - masz pytania napisz...",
    "instagramStatus": "ok"
  },
  {
    "id": 88,
    "name": "",
    "title": "Soccer Barbershop",
    "category": "Краса",
    "subcategory": "Барбершоп",
    "phone": "",
    "website": "https://soccerbarbershop.booksy.com/a/",
    "social": "",
    "instagram": "",
    "description": "Рекомендовали именно в ответ на запрос \"барбера українку/українця\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 89,
    "name": "Олександра",
    "title": "Олександра",
    "category": "Здоровʼя",
    "subcategory": "Стоматолог (лікування каналів під мікроскопом)",
    "phone": "+48 452 641 652",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Принимает в Жорах (Żory)",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 90,
    "name": "",
    "title": "dr_ersteniuk",
    "category": "Здоровʼя",
    "subcategory": "Трихолог",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/dr_ersteniuk",
    "instagram": "dr_ersteniuk",
    "description": "Рекомендовали в ответ на вопрос про трихолога",
    "communityMatch": true,
    "avatar": "/avatars/dr_ersteniuk.jpg",
    "instagramTitle": "Трихолог /Варшава Уляна Ерстенюк",
    "instagramFollowers": "11.8k",
    "instagramFollowing": "222",
    "instagramBio": "Лікування волосся та шкіри голови - Ліцензія PST 074 - Засновниця @tress_therapy_centr",
    "instagramStatus": "ok"
  },
  {
    "id": 91,
    "name": "Андрій",
    "title": "MM Legally Company",
    "category": "Послуги",
    "subcategory": "Легалізація (карта побиту)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/mm_legallycompany",
    "instagram": "mm_legallycompany",
    "description": "За три месяца оформили карту, личная рекомендация",
    "communityMatch": true,
    "avatar": "/avatars/mm_legallycompany.jpg",
    "instagramTitle": "Карта Побыту|Легализация в Польше Katowice",
    "instagramFollowers": "1,069",
    "instagramFollowing": "112",
    "instagramBio": "Полное сопровождение по Карте Побыту - Бесплатная консультация - ul.Przemysłowa 10/226, Katowice",
    "instagramStatus": "ok"
  },
  {
    "id": 92,
    "name": "Ірина",
    "title": "Ірина",
    "category": "Здоровʼя",
    "subcategory": "Масаж",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Массажистка с медицинским образованием, может подсказать к какому врачу обратиться",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 93,
    "name": "Олег",
    "title": "Олег",
    "category": "Послуги",
    "subcategory": "Вантажні перевезення / переїзди",
    "phone": "+48723386214",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Рекомендация услуг перевозки",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 94,
    "name": "Аня",
    "title": "Magiczne Dłoni",
    "category": "Краса",
    "subcategory": "Нігті / салон",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"всі дівчата українки працюють\", ходят к Ане не первый год",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 95,
    "name": "Катерина Лазарєва",
    "title": "Катерина Лазарєва",
    "category": "Юридичні послуги",
    "subcategory": "Адвокат (сімейне право, дистанційно)",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Самопост: адвокат с 20-летним стажем в семейном праве Украины, ведёт дела без личного присутствия клиента",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 96,
    "name": "",
    "title": "Dr. Krashchenko",
    "category": "Здоровʼя",
    "subcategory": "Косметолог / дерматохірург",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/dr.krashchenko",
    "instagram": "dr.krashchenko",
    "description": "В тексте прямо: косметолог \"з Києва їде до Катовіце\"; в другом сообщении подтверждено \"косметолог приїздить з Києва. Лікар дерматохірірг\" (аккаунт https://www.instagram.com/dr.krashcha), регулярно учится в Италии и Франции",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "Profile isn't available • Instagram",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "[FAILED: profile_not_available]",
    "instagramStatus": "failed"
  },
  {
    "id": 97,
    "name": "Анна Івахненко",
    "title": "Tour Ukraine",
    "category": "Послуги",
    "subcategory": "Доставка посилок (Україна-Польща)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/tourukraine",
    "instagram": "tourukraine",
    "description": "Приезжает в Катовице прямо к автовокзалу",
    "communityMatch": true,
    "avatar": "/avatars/tourukraine.jpg",
    "instagramTitle": "Автобусні квитки до Європи | TOURUKRAINE",
    "instagramFollowers": "107k",
    "instagramFollowing": "1",
    "instagramBio": "Надійні рейси щодня - Квитки онлайн за 2 хвилини - Підтримка з 08:00 до 23:00 - Бронюй вже зараз",
    "instagramStatus": "ok"
  },
  {
    "id": 98,
    "name": "",
    "title": "UKS Synergia",
    "category": "Заклади",
    "subcategory": "Спортивна секція (діти)",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"укр., тренер та група\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 99,
    "name": "Ігор Суббота",
    "title": "Ігор Суббота",
    "category": "Послуги",
    "subcategory": "Туроператор",
    "phone": "+380664799898",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Рекомендован в ответ на запрос туроператора; летает через него 4 года",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 100,
    "name": "Петро",
    "title": "Петро",
    "category": "Послуги",
    "subcategory": "Автоелектрик",
    "phone": "733 308 219",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "\"Проверенный мастер\", ремонт электроники в машине",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 101,
    "name": "",
    "title": "Drukidruk.pl",
    "category": "Послуги",
    "subcategory": "Поліграфія / друк",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/drukidruk.pl",
    "instagram": "drukidruk.pl",
    "description": "В тексте прямо: \"Українці\"",
    "communityMatch": true,
    "avatar": "/avatars/drukidruk.pl.jpg",
    "instagramTitle": "Druki Druk | DTF Print Polska",
    "instagramFollowers": "514",
    "instagramFollowing": "72",
    "instagramBio": "Profesjonalny DTF Druk od 1 sztuki - Twój projekt lub nasza grafika - Szybka dostawa w całej Polsce - Jakość premium...",
    "instagramStatus": "ok"
  },
  {
    "id": 102,
    "name": "Anastasiia Novgorodska",
    "title": "Anastasiia Novgorodska",
    "category": "Послуги",
    "subcategory": "Рієлтор",
    "phone": "+48 515 752 106",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Сама предлагает помощь в ответ на запрос риелтора в Катовице",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 103,
    "name": "Євген Жарков",
    "title": "Євген Жарков",
    "category": "Послуги",
    "subcategory": "Ведучий подій (весілля)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/zharkov.evgen",
    "instagram": "zharkov.evgen",
    "description": "Именно ведущий, не тамада",
    "communityMatch": true,
    "avatar": "/avatars/zharkov.evgen.jpg",
    "instagramTitle": "ведучий Варшава • Краків • Вроцлав • Євгеній Жарков",
    "instagramFollowers": "3,176",
    "instagramFollowing": "368",
    "instagramBio": "ведучий, за якого не соромно перед батьками, без шаблону і крінжа, створюю романтичні церемонії з гумором...",
    "instagramStatus": "ok"
  },
  {
    "id": 104,
    "name": "Віка",
    "title": "Віка",
    "category": "Послуги",
    "subcategory": "Бухгалтерія (розрахунок PIT)",
    "phone": "0971140681",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Помогает с расчётом PIT (налоговая декларация); украинский формат номера телефона",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 105,
    "name": "Олег",
    "title": "Олег",
    "category": "Послуги",
    "subcategory": "Вантажні перевезення (Україна-Польща)",
    "phone": "+380681119595",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Возит посылки/грузы, в т.ч. в Каменец-Подольский; украинский номер телефона",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 106,
    "name": "",
    "title": "Без назви",
    "category": "Послуги",
    "subcategory": "Присяжний перекладач (укр-пол)",
    "phone": "668 903 563",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Рекомендовали дважды (также в др. чатах) для присяжного перевода",
    "communityMatch": false,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 107,
    "name": "Roman Narepekha",
    "title": "Roman Narepekha",
    "category": "Здоровʼя",
    "subcategory": "Ортопед",
    "phone": "",
    "website": "https://www.znanylekarz.pl/roman-narepekha/ortopeda/katowice",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"рекомендую, українець\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 108,
    "name": "Лиза",
    "title": "Лиза",
    "category": "Краса",
    "subcategory": "Масаж / релакс",
    "phone": "+48 576 774 727",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"говорят по-українськи\"; студия +48 537 452 067",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 109,
    "name": "Юля",
    "title": "Юля",
    "category": "Освіта",
    "subcategory": "Репетитор англійської",
    "phone": "097 46982-51",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Рекомендовали из личного опыта; украинский формат номера телефона",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 110,
    "name": "Андрей",
    "title": "Андрей",
    "category": "Послуги",
    "subcategory": "Ремонт кавомашин",
    "phone": "571067454",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Ремонт оборудования любой сложности, Катовице",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 111,
    "name": "Анжеліка Дьячук",
    "title": "Zdorovo Katowice",
    "category": "Здоровʼя",
    "subcategory": "УЗД (діагностика)",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "150 zł, УЗИ груди; рекомендована именно в ответ на запрос \"где делают украинцы\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 112,
    "name": "",
    "title": "Без назви",
    "category": "Послуги",
    "subcategory": "Автоскло / ремонт лобового скла",
    "phone": "",
    "website": "",
    "social": "https://www.facebook.com/share/1AnLQQBfnk/",
    "instagram": "",
    "description": "В тексте прямо: \"міняла в українця з Тихих\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 113,
    "name": "",
    "title": "Alyonka Masalyova",
    "category": "Краса",
    "subcategory": "Тату",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/alyonka_masalyova",
    "instagram": "alyonka_masalyova",
    "description": "В тексте прямо: \"Українка\", делала первое тату на шее",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "Tattoo Katowice",
    "instagramFollowers": "11.2k",
    "instagramFollowing": "128",
    "instagramBio": "Tattoo Katowice 9 lat doświadczenia Katowice Owner @tattoo_katowice_ tattoo tattoo Malta 🇲🇹 Gozo обучение",
    "instagramStatus": "ok"
  },
  {
    "id": 114,
    "name": "",
    "title": "Українська студія танців (Тихи)",
    "category": "Заклади",
    "subcategory": "Танцювальна студія",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Латиноамериканские танцы, бесплатное занятие по воскресеньям, город Тихы",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 115,
    "name": "Олександра",
    "title": "Олександра",
    "category": "Здоровʼя",
    "subcategory": "Стоматолог (для підлітків)",
    "phone": "+380500667136",
    "website": "",
    "social": "Viber: +380500667136",
    "instagram": "",
    "description": "Принимает в Катовице, plac Wolności",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 116,
    "name": "Артем",
    "title": "Артем",
    "category": "Здоровʼя",
    "subcategory": "Масаж",
    "phone": "795034455",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Массаж помог с болью в спине",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 117,
    "name": "Яна Степанцова",
    "title": "Яна Степанцова",
    "category": "Здоровʼя",
    "subcategory": "Масаж",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/jana.stepantsova",
    "instagram": "jana.stepantsova",
    "description": "Помогла с болью в спине, профессионал своего дела",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "Profile isn't available • Instagram",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "[FAILED: not_found]",
    "instagramStatus": "failed"
  },
  {
    "id": 118,
    "name": "Злата",
    "title": "Злата",
    "category": "Здоровʼя",
    "subcategory": "Психолог",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Самопост: обращается \"дорогі співвітчизниці\", проводит консультации",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 119,
    "name": "",
    "title": "Dr. Liliia Nikulina",
    "category": "Здоровʼя",
    "subcategory": "Лікар (онлайн-консультації)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/dr.liliia_nikulina",
    "instagram": "dr.liliia_nikulina",
    "description": "\"Чудова лікарка\", консультирует онлайн",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 120,
    "name": "",
    "title": "Dr. Krivenko Gastro",
    "category": "Здоровʼя",
    "subcategory": "Гастроентеролог",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/dr.krivenkogastro",
    "instagram": "dr.krivenkogastro",
    "description": "Рекомендован без дополнительного контекста",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 121,
    "name": "",
    "title": "Zdorovo (Katowice)",
    "category": "Здоровʼя",
    "subcategory": "Гінекологія (скринінг)",
    "phone": "815 032 278",
    "website": "",
    "social": "Instagram: zdorovo.pl",
    "instagram": "",
    "description": "Акция для украинских женщин — бесплатная кольпоскопия и онко-тест",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 122,
    "name": "",
    "title": "Tru Coffee Machines",
    "category": "Послуги",
    "subcategory": "Магазин професійної техніки (кавомашини)",
    "phone": "",
    "website": "https://tru-coffee-machines.pl/",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"Це українці\", магазин рядом с IKEA Катовице",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 123,
    "name": "Олег",
    "title": "Олег",
    "category": "Нерухомість",
    "subcategory": "Рієлтор",
    "phone": "794-182-180",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Рекомендован в ответ на запрос риелтора",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 124,
    "name": "Людмила Борисенко",
    "title": "Людмила Борисенко",
    "category": "Нерухомість",
    "subcategory": "Рієлтор",
    "phone": "+48 666 979 969",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Рекомендована в ответ на запрос риелтора",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 125,
    "name": "Ольга Котик",
    "title": "Ольга Котик",
    "category": "Юридичні послуги",
    "subcategory": "Адвокат (сімейне право, довіреності)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/adwokat_olga_kotyk",
    "instagram": "adwokat_olga_kotyk",
    "description": "Личная рекомендация для семейных дел и доверенностей",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 126,
    "name": "",
    "title": "KPW Auto",
    "category": "Послуги",
    "subcategory": "Автосалон (продаж/купівля авто)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/kpw_auto_",
    "instagram": "kpw_auto_",
    "description": "Есть сотрудник из Украины",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 127,
    "name": "Наталія Щукіна",
    "title": "Zdorovo",
    "category": "Здоровʼя",
    "subcategory": "Лікар",
    "phone": "",
    "website": "https://zdorovo.pl/doctor/nataliia-shchukina",
    "social": "",
    "instagram": "",
    "description": "Запись удобная, через инфолинию, говорят по-украински",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 128,
    "name": "Андрій Миколайович Тіщенко",
    "title": "Zdorovo (Сосновец)",
    "category": "Здоровʼя",
    "subcategory": "Офтальмолог (зокрема дитячий)",
    "phone": "815 032 278",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Начинает приём со следующей недели; запись на украиноязычную инфолинию",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 129,
    "name": "",
    "title": "IVANCOM",
    "category": "Послуги",
    "subcategory": "Доставка посилок (Польща-Україна)",
    "phone": "",
    "website": "",
    "social": "Instagram: @ivancom.poland",
    "instagram": "",
    "description": "Быстрая и надёжная доставка в обе стороны, косметика/золото-серебро и др.",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 130,
    "name": "Olena Lypovska",
    "title": "Olena Lypovska",
    "category": "Здоровʼя",
    "subcategory": "ЛОР",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Рекомендована именно в ответ на запрос \"українського лора\"; есть на znanylekarz",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 131,
    "name": "Артем",
    "title": "Артем",
    "category": "Послуги",
    "subcategory": "Евакуатор",
    "phone": "+48 733 716 707",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Рекомендован в ответ на запрос эвакуатора",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 132,
    "name": "",
    "title": "Pracownia Brigadir",
    "category": "Послуги",
    "subcategory": "Столярна майстерня (скриньки, топери)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/pracownia.brigadir",
    "instagram": "pracownia.brigadir",
    "description": "В тексте прямо: \"Менеджери розмовляють українською\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 133,
    "name": "Алена",
    "title": "Приватный садик",
    "category": "Заклади",
    "subcategory": "Дитячий садок",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"найкращий приватний садок з українськими і польськими вихователями\"; ~1000 зл/мес + питание",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 134,
    "name": "",
    "title": "Kosmetolog Tarasova Katowice",
    "category": "Здоровʼя",
    "subcategory": "Трихолог / косметолог",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/kosmetolog_tarasova_katowice",
    "instagram": "kosmetolog_tarasova_katowice",
    "description": "Рекомендована именно в ответ на запрос \"українського трихолога\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 135,
    "name": "Лена",
    "title": "Beauty Atelier LS",
    "category": "Краса",
    "subcategory": "Епіляція",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/beauty_atelier_ls",
    "instagram": "beauty_atelier_ls",
    "description": "В тексте прямо: \"тут українка Лена робить класно\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 136,
    "name": "",
    "title": "A.kittttty",
    "category": "Краса",
    "subcategory": "Нігті",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/a.kittttty",
    "instagram": "a.kittttty",
    "description": "В тексте прямо: \"якшо шо українка\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 137,
    "name": "Дмитро",
    "title": "Дмитро",
    "category": "Послуги",
    "subcategory": "Доставка посилок (Польща-Україна)",
    "phone": "+380976410967",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "По субботам забирает посылки для отправки в Украину",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 138,
    "name": "",
    "title": "Tanita Zumba",
    "category": "Заклади",
    "subcategory": "Танці (зумба)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/tanita_zumba.kato",
    "instagram": "tanita_zumba.kato",
    "description": "В тексте прямо: \"група лише з нашими українськими дівчатами\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 139,
    "name": "Ирина Токаревич",
    "title": "Ирина Токаревич",
    "category": "Здоровʼя",
    "subcategory": "Ортодонт",
    "phone": "+380919221121",
    "website": "",
    "social": "Viber",
    "instagram": "",
    "description": "Рекомендована в ответ на запрос ортодонта; украинский номер телефона",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 140,
    "name": "Ольга",
    "title": "Ольга",
    "category": "Послуги",
    "subcategory": "Присяжний перекладач",
    "phone": "+48 881 377 992",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Присяжный переводчик",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 141,
    "name": "",
    "title": "Butterfly (Siemianowice)",
    "category": "Заклади",
    "subcategory": "Спортивна секція (акробатика, гімнастика)",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"український тренер і більшість українських дітей\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 142,
    "name": "",
    "title": "Carmen Dance Center (Katowice)",
    "category": "Заклади",
    "subcategory": "Танцювальна студія",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "\"Польські тренера, але є і український тренер з джаз фанк\" — в основном польская школа",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 143,
    "name": "Міцкевич",
    "title": "Міцкевич",
    "category": "Здоровʼя",
    "subcategory": "Гінеколог",
    "phone": "+48 536 106 300",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"Вона крута, наша\" — рекомендована в ответ на запрос \"нашого\" гинеколога",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 144,
    "name": "",
    "title": "Lova Estate (Katowice)",
    "category": "Нерухомість",
    "subcategory": "Рієлтор",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/lova.estate.katowice",
    "instagram": "lova.estate.katowice",
    "description": "Помогла с поиском квартиры, быстро и профессионально",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 145,
    "name": "",
    "title": "Dynasty Stomatology (Krakow)",
    "category": "Здоровʼя",
    "subcategory": "Стоматолог",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/dynasty_stomatology",
    "instagram": "dynasty_stomatology",
    "description": "Врач из Запорожья; \"Ми ходили в Катовіце до української лікарки, але... перевелися... дуже задоволені\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 146,
    "name": "Євген",
    "title": "Records.pl",
    "category": "Краса",
    "subcategory": "Барбершоп",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/records.pl",
    "instagram": "records.pl",
    "description": "В тексте прямо: \"Працюють тільки українці\", район Трёх ставов",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 147,
    "name": "Olena Lahutina",
    "title": "Olena Lahutina",
    "category": "Послуги",
    "subcategory": "Туроператор",
    "phone": "",
    "website": "",
    "social": "Instagram: @OlenaLahutina",
    "instagram": "",
    "description": "\"Турбота і сервіс на найвищому рівні\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 148,
    "name": "",
    "title": "Українське СТО (Ruda Śląska)",
    "category": "Послуги",
    "subcategory": "Автосервіс",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Адрес: Warszawska 9, Ruda Śląska. Доступные цены, качественная работа",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 149,
    "name": "",
    "title": "Кав'ярня (чизкейки)",
    "category": "Заклади",
    "subcategory": "Кафе",
    "phone": "",
    "website": "",
    "social": "https://maps.app.goo.gl/fYTKhHG5ZqTB5roy6",
    "instagram": "",
    "description": "В тексте прямо: \"власниця українка, тому там так приємно\"; очень вкусные чизкейки",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 150,
    "name": "",
    "title": "Материнка",
    "category": "Заклади",
    "subcategory": "Українська школа",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Украинская школа (пока есть проблемы с легализацией в польской системе образования)",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 151,
    "name": "",
    "title": "Гуртки для детей (Катовице)",
    "category": "Заклади",
    "subcategory": "Гуртки (карате, гімнастика, танці, англійська, моделінг, образотворче мистецтво)",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Перечислены кружки именно с украинскими преподавателями (в отличие от польских — теннис, современные танцы)",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 152,
    "name": "Ірина Галенко",
    "title": "Centrum Medyczne Graniczna",
    "category": "Здоровʼя",
    "subcategory": "Сімейний лікар",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Рекомендована именно в ответ на запрос \"сімейного лікаря, бажано українку\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 153,
    "name": "Олег",
    "title": "Олег",
    "category": "Здоровʼя",
    "subcategory": "Стоматолог",
    "phone": "+48517162746",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "\"Офигенный стоматолог\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 154,
    "name": "Арсен",
    "title": "Арсен",
    "category": "Здоровʼя",
    "subcategory": "Фізіотерапевт",
    "phone": "+48 518 125 146",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Помогает со спиной, недорого",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 155,
    "name": "Дмитро",
    "title": "Дмитро",
    "category": "Послуги",
    "subcategory": "Автомеханік",
    "phone": "+48536583113",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Рекомендован в ответ на запрос автомеханика",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 156,
    "name": "",
    "title": "Soul Jewelry PL",
    "category": "Послуги",
    "subcategory": "Ювелірний (обручки)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/souljewelrypl",
    "instagram": "souljewelrypl",
    "description": "В тексте прямо: \"це українська фірма\", изготавливают во Львове, физический магазин в Кракове",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 157,
    "name": "",
    "title": "Bar Garden Katowice",
    "category": "Заклади",
    "subcategory": "Бар",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/bar.garden.katowice",
    "instagram": "bar.garden.katowice",
    "description": "В тексте прямо: \"Це український заклад\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 158,
    "name": "Андрій",
    "title": "Андрій",
    "category": "Здоровʼя",
    "subcategory": "Стоматолог (протетика)",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"Українські лікарі\" — протетика, лечение, экстракция, центр города",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 159,
    "name": "Олена",
    "title": "Олена",
    "category": "Здоровʼя",
    "subcategory": "Стоматолог-ортодонт",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"Українські лікарі\" — ортодонт, лечение каналов, реставрация",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 160,
    "name": "Ольга Ліпкевич",
    "title": "Ольга Ліпкевич",
    "category": "Здоровʼя",
    "subcategory": "Трихолог",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/olga_lipkevych",
    "instagram": "olga_lipkevych",
    "description": "В тексте прямо: \"вона українка\", помогла с выпадением волос, принимает в Катовице",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 161,
    "name": "Марина",
    "title": "Марина",
    "category": "Здоровʼя",
    "subcategory": "Стоматолог",
    "phone": "32 770-22-32",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Врач из Харькова, приём по NFZ, запись заранее (ассистент — полька)",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 162,
    "name": "Михайло Ясінський",
    "title": "Михайло Ясінський",
    "category": "Здоровʼя",
    "subcategory": "Сімейний лікар",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"наш сімейний лікар в Руді\"; адреса: św. Pawła 11a и ул. Mazurska (вт, чт 16-18)",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 163,
    "name": "",
    "title": "Паляниця",
    "category": "Заклади",
    "subcategory": "Ресторан (украинская кухня)",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"Українська кухня\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 164,
    "name": "",
    "title": "Acaya",
    "category": "Заклади",
    "subcategory": "Ресторан",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "В тексте прямо: \"просто український заклад\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 165,
    "name": "Вікторія",
    "title": "Вікторія",
    "category": "Освіта",
    "subcategory": "Репетитор англійської",
    "phone": "+380 63 428 38 47",
    "website": "",
    "social": "Telegram: @taranViki",
    "instagram": "",
    "description": "\"Номер український, але вона в Польщі\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 166,
    "name": "",
    "title": "Pani Bus",
    "category": "Послуги",
    "subcategory": "Пассажироперевозки (Украина-Польша)",
    "phone": "+380 (67) 761 74 74",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Украинский номер телефона",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 167,
    "name": "",
    "title": "Vektor",
    "category": "Послуги",
    "subcategory": "Пассажироперевозки (Украина-Польша)",
    "phone": "+380 (98) 356 57 51",
    "website": "",
    "social": "https://www.instagram.com/vektor_24poland",
    "instagram": "vektor_24poland",
    "description": "Украинский номер телефона; страница \"суто українська\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 168,
    "name": "",
    "title": "Belinens UA",
    "category": "Послуги",
    "subcategory": "Магазин текстиля (постельное бельё)",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/belinens_ua",
    "instagram": "belinens_ua",
    "description": "В тексте прямо: \"Це наш Миколаїв відшиває\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 169,
    "name": "",
    "title": "Dr. Dermatokosmetolog",
    "category": "Здоровʼя",
    "subcategory": "Косметолог",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/dr.dermatokosmetolog",
    "instagram": "dr.dermatokosmetolog",
    "description": "В тексте прямо: \"Украинка, с мед образованием\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 170,
    "name": "",
    "title": "Viktoriya Nails Kharkov",
    "category": "Краса",
    "subcategory": "Нігті",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/viktoriya.nails.kharkov",
    "instagram": "viktoriya.nails.kharkov",
    "description": "Мастер маникюра из Харькова (по названию аккаунта)",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 171,
    "name": "",
    "title": "Your Celebration",
    "category": "Послуги",
    "subcategory": "Аниматоры для праздников",
    "phone": "",
    "website": "",
    "social": "https://www.instagram.com/your_celebration.com.pl",
    "instagram": "your_celebration.com.pl",
    "description": "В тексте прямо: \"контакти українок-аніматорів\"",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 172,
    "name": "Наталия",
    "title": "Наталия",
    "category": "Здоровʼя",
    "subcategory": "Массаж (лечебный)",
    "phone": "+48 505 081 095",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Опыт более 25 лет, личная рекомендация",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 173,
    "name": "Юрій Лукащук",
    "title": "Юрій Лукащук",
    "category": "Послуги",
    "subcategory": "Грузоперевозки (посылки, Новая почта)",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Рекомендован после успешной пересылки посылки",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  },
  {
    "id": 174,
    "name": "Дмитро Жаворонков",
    "title": "Дмитро Жаворонков",
    "category": "Здоровʼя",
    "subcategory": "Флеболог",
    "phone": "",
    "website": "",
    "social": "",
    "instagram": "",
    "description": "Gliwice, ul. Dubois 16, запись через Znany Lekarz",
    "communityMatch": true,
    "avatar": "",
    "instagramTitle": "",
    "instagramFollowers": "",
    "instagramFollowing": "",
    "instagramBio": "",
    "instagramStatus": ""
  }
];
